## add Empty data for next year in residential table when current date is equals to last day of current year
def Add_YearlyData(fiscal_year):
	#fiscal_year = str(year) + '-' + str(year+1) # get fiscal year from current year
	# create insert query to insert data from fiscal year Jun to July
	insert_Q = "INSERT INTO [participant].[ResidentialDashboard] ([july_value],[aug_value],[sept_value],[oct_value],[nov_value],[dec_value],[jan_value],[feb_value],[march_value],[april_value],[may_value],[june_value],[fiscal_year],[parameter],[parameter_display_value],[is_manual]) VALUES "
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Bed Count', 'Bed Count', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Average per night', 'Average per Night', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Total Bed Count minus GPD - Actual', 'Total Bed Count minus GPD - Actual', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Total Bed Count minus GPD', 'Total Bed Count minus GPD', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Total number of meals served', 'Total Number of Meals Served', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Social Detox  Metro', 'Social Detox  Metro', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Average time per person (minutes)', 'Average Time per Person (minutes)', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Social Detox - non Metro', 'Social Detox - Non Metro', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Provided Clothing', 'Provided Clothing', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Laundry Services Give', 'Laundry Services Give', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Vanderbilt Billing', 'Vanderbilt Billing', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Vanderbilt Billing Number of Participants', 'Number of Participants', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'MTMHI Billing', 'MTMHI Billing', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'MTMHI Billing Number of Participants', 'Number of Participants', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'RHP Billing', 'RHP Billing', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'RHP Billing Number of Participants', 'Number of Participants', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'ARP Billing', 'ARP Billing', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'ARP Billing Number of Participants', 'Number of Participants', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Fee Paid Transitional Billing - Suspended', 'Fee Paid Transitional Billing - Suspended', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Fee Paid Transitional Billing - Suspended Number of Participants', 'Number of Participants', 1),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Entered Pending/Seeking', 'Entered Pending/Seeking', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Went to treatment', 'Went to Treatment', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Connected to Mental Health Services', 'Connected to Mental Health Services', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Connected to SOAR', 'Connected to SOAR', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'SSI or SSDI check started', 'SSI or SSDI Check Started', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Employment', 'Employment', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Moved into housing', 'Moved Into Housing', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Moved into institutional living', 'Moved Into Institutional Living', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Attended Apartment Lunch Outing', 'Attended Apartment Lunch Outing', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Attended Apartment Grocery Outing', 'Attended Apartment Grocery Outing', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Attended Apartment Pantry', 'Attended Apartment Pantry', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Attended Monday Night Dinner', 'Attended Monday Night Dinner', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Attended Monday Outside Meeting', 'Attended Monday Outside Meeting', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Attended Monthly VA Dinner', 'Attended Monthly VA Dinner', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Recuperative Care Referrals Received', 'Recuperative Care Referrals Received', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Recuperative Care Referrals Accepted', 'Recuperative Care Referrals Accepted', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'Recuperative Care Referrals Arrived', 'Recuperative Care Referrals Arrived', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'VA Referrals Received', 'VA Referrals Received', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'VA Referrals Accepted', 'VA Referrals Accepted', 0),"
	insert_Q = insert_Q + "(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '"+str(fiscal_year)+"', 'VA Referrals Arrived', 'VA Referrals Arrived', 0)"
	
	system.db.runPrepUpdate(insert_Q, [])		
