SELECT [id]
      ,[month]
      ,[day]
      ,[year]
      ,Concat([day],'-',LEFT([month], 3)) as 'Date'
      ,[generalPopLunch]
      ,[cafeMWF]
      ,[snackPacks]
      ,[morningCensus]
      ,[dayCensus]
      ,[showers]
      ,[laundry]
      ,[mailCheckHMS] as "mailCheckRITI"
      ,[morningNews]
      ,[noOfClasses]
      ,[classAttendance]
      ,[inPersonStore]
      ,[navigationService]
      ,[footClinic]
      ,[isClosed]
      ,[isWeekend]
      ,ISNULL([notes],'') as 'notes'
      ,[navigationPhoneAccess]
      ,[laundryMissed]
      ,[mailMissed]
      ,[showersMissed] 
      ,[phoneComputerAccessMissed]
  FROM [participant].[HopeUDashboard]
  WHERE [id] = :id